name: dithered
wallpapers:
  - author_name: Eastman Kodak Company (licensed for unrestricted use)
    author_url: http://r0k.us/graphics/kodak/index.html
    image_url: https://r0k.us/graphics/kodak/kodak/kodim21.png
    modified: true
  - author_name: Eastman Kodak Company (licensed for unrestricted use)
    author_url: http://r0k.us/graphics/kodak/index.html
    image_url: https://r0k.us/graphics/kodak/kodak/kodim22.png
    modified: true
  - author_name: Eastman Kodak Company (licensed for unrestricted use)
    author_url: http://r0k.us/graphics/kodak/index.html
    image_url: https://r0k.us/graphics/kodak/kodak/kodim05.png
    modified: true
  - author_name: Eastman Kodak Company (licensed for unrestricted use)
    author_url: http://r0k.us/graphics/kodak/index.html
    image_url: https://r0k.us/graphics/kodak/kodak/kodim08.png
    modified: true
