name: mandelbrot
wallpapers:
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_lavender.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_sky.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_rosewater.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_pink.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_blue.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_yellow.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_red.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_peach.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_maroon.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_green.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_teal.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_lavender.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_green.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_magenta.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_red.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_lavender.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_red.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_teal.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_maroon.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_yellow.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_yellow.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_pink.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_blue.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_flamingo.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_rosewater.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_maroon.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_pink.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_blue.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_flamingo.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_sky.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_magenta.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_magenta.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_peach.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_side_sky.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_green.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_teal.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_full_rosewater.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: mandelbrot_gap_peach.png
    modified: false
